---
application:
  name: "umami"
  project: "stats"
  organization: "QoveryCommunity"
  storage:
  - name: "disk"
    size: "60"
    type: "fast_ssd"
    mount_point: "/"
databases:
- type: "MYSQL"
  name: "sqlo"
  version: "8.0"
routers:
- name: "main-umami"
  routes:
  - application_name: "umami"
    paths:
    - "/*"
