---
application:
  name: "umami"
  project: "statu"
  organization: "QoveryCommunity"
  storage:
  - name: "disk"
    size: "30"
    type: "fast_ssd"
    mount_point: "/mnt/disk"
databases:
- type: "POSTGRESQL"
  name: "dbp"
  version: "10"
routers:
- name: "main-umami"
  routes:
  - application_name: "umami"
    paths:
    - "/*"
